[extend]
useDefault = true

[[allowlists]]
description = "Exact public extension identity key; no private key exists in this repository."
regexTarget = "match"
regexes = [
  '''MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxdY273V1FgFZBek3h1SQLcqsHs3jyhkvsEB91KQkdci/kDZTmrf4BoW4/fi4N2CkWXhSt\+Zdba\+9Q36nf9Vl1GaYJJb6aKH33dkI3zKbehaWkmDDpbxGtCOFhQEt/nDcmyUzLNRTNYACAxl5Ij7N9M6VIW1ws5yJg6ph3Oqq90/KE8pNhRlt77hcClAbvwdxy8J230Gb0dKGTV6acbY0vawQarYHMgbA1rTzjdkjmvSGEpLACmDSeI64PgDFeNK3wKbZP\+Rtrj0s4\+YMVE\+FxZSvq9KWMJHs0HcUCBZ\+xfgbl9DWCNJv536UTvz30nC5nt3kU7HhN1NWUGrqUMIWlwIDAQAB'''
]
